spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  flyway:
    baseline-on-migrate: false
    check-location: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./test/db
    driver-class-name: org.h2.Driver
    username: sa
    password:



