create sequence hibernate_sequence start with 1 increment by 1;

create table groups (
    id bigint not null,
    group_number bigint,
    primary key (id)
                    );

create table students (
    id bigint generated by default as identity,
    first_name varchar(255),
    last_name varchar(255),
    group_id bigint,
    primary key (id)
                      );

create table students_subjects (
    students_id bigint not null,
    subjects_id bigint not null
                               );

create table subjects (
    id bigint not null,
    name_subject varchar(255),
    primary key (id)
                      );

alter table students add constraint
    FKmsev1nou0j86spuk5jrv19mss foreign key
        (group_id) references groups;


alter table students_subjects add constraint
    FK2pm1dsehrlqa1smxrki4f9nl3 foreign key
        (subjects_id) references subjects;


alter table students_subjects add constraint
    FK5o245jepbd6cuqaqksiegaphy foreign key
        (students_id) references students;